export const VI = {
    MainComponent: {
        "Dashboard": "Thống kê",
        "Dock Scheduling": "Lập kế hoạch",
        "Inbound": "Nhập",
        "ASN/Receipt": "Đơn hàng nhập",
        "Inbound Report": "Báo cáo hàng nhập",
        "Outbound": "Xuất",
        "Shipment Order": "Đơn hàng xuất",
        "Outbound Report": "Báo cáo hàng xuất",
        "Inventory": "Tồn",
        "Inventory List": "Danh sách tồn kho",
        "Pallet In Date": "Số pallet trong ngày",
        "Move": "Di chuyển hàng",
        "Adjustment": "Điều chỉnh số lượng",
        "Change Status": "Thay đổi trạng thái",
        "Lot Update": "Cập nhật thông tin",
        "Transaction": "Lịch sử thao tác",
        "Stock Count": "Kiểm đếm tồn kho",
        "Post Stock": "Cập nhật tồn kho",
        "Pre Move": "Di chuyển hàng sau",
        "Internal Transfer": "Chuyển hàng nội bộ",
        "Billing": "Tính phí",
        "Charge Type": "Loại chi phí",
        "Charge": "Thiết lập chi phí",
        "Tariff": "Đơn giá",
        "Configuration": "Thiết lập",
        "Customer": "Khách hàng",
        "Customer Group": "Nhóm khách hàng",
        "Pack": "Quy cách chất xếp",
        "Location": "Vị trí",
        "Zone": "Khu vực",
        "Carrier": "Nhà vận chuyển",
        "Line": "Khu vực tập kết",
        "Supplier": "Nhà cung cấp",
        "Allocate": "Chiến lược lấy hàng",
        "Putaway": "Chiến lược xếp hàng",
        "System Code": "Mã hệ thống",
        "Item": "Hàng hóa",
        "BOM": "Đóng gói",
        "Guide": "Hướng dẫn sử dụng",
        "Configuration Guide": "Cài đặt",
        "Dock ASN": "Lập kế hoạch đơn nhập",
        "Dock SO": "Lập kế hoạch đơn xuất",
        "Drop Id" : "Drop Id",
        "Storage List" : "Lưu trữ",
        "Check In" : "Cổng kiểm tra",
        "Inventory Report" : "Báo cáo tồn kho",
        "Visualize": "MÔ HÌNH",
        "visualize" : "Mô hình",
        "newwarehouse": "Kho mới"
    }
}

export const EN = {
    MainComponent: {
        "Dashboard": "DASHBOARD",
        "Dock Scheduling": "DOCK SCHEDULING",
        "Inbound": "INBOUND",
        "ASN/Receipt": "ASN/Receipt",
        "Inbound Report": "Inbound Report",
        "Outbound": "OUTBOUND",
        "Shipment Order": "Shipment Order",
        "Outbound Report": "Outbound Report",
        "Inventory": "INVENTORY",
        "Inventory List": "Inventory List",
        "Pallet In Date": "Pallet In Date",
        "Move": "Move",
        "Adjustment": "Adjustment",
        "Change Status": "Change Status",
        "Lot Update": "Lot Update",
        "Transaction": "Transaction",
        "Stock Count": "Stock Count",
        "Post Stock": "Post Stock",
        "Pre Move": "Pre Move",
        "Internal Transfer": "Internal Transfer",
        "Billing": "BILLING",
        "Charge Type": "Charge Type",
        "Charge": "Charge",
        "Tariff": "Tariff",
        "Configuration": "CONFIGURATION",
        "Customer": "Customer",
        "Customer Group": "Customer Group",
        "Pack": "Pack",
        "Location": "Location",
        "Zone": "Zone",
        "Carrier": "Carrier",
        "Line": "Line",
        "Supplier": "Supplier",
        "Allocate": "Allocate",
        "Putaway": "Putaway",
        "System Code": "System Code",
        "Item": "Item",
        "BOM": "BOM",
        "Guide": "Guide",
        "Configuration Guide": "Configuration Guide",
        "Dock ASN": "Dock ASN",
        "Dock SO": "Dock SO",
        "Drop Id": "Drop Id",
        "Storage List" : "Storage List",
        "Check In" : "Check In",
        "Inventory Report" : "Inventory Report",
        "Visualize" : "VISUALIZE",
        "visualize" : "Visualize",
        "newwarehouse": "warehouse"
    }
}